config/routes.rb
Univer::Application.routes.draw do
  resources :journals

  resources :lessons

  resources :students

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  attr_accessible :lesson_id, :mark, :student_id

  belongs_to :lesson
  belongs_to :student

  validates :mark, :presence => true,
            :inclusion => 1..5
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :name

  has_many :journals
  has_and_belongs_to_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name

  has_many :journals
  has_and_belongs_to_many :lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @journals }
    end
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    @journal = Journal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @journal }
    end
  end

  # GET /journals/new
  # GET /journals/new.json
  def new
    @journal = Journal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @journal }
    end
  end

  # GET /journals/1/edit
  def edit
    @journal = Journal.find(params[:id])
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(params[:journal])

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render json: @journal, status: :created, location: @journal }
      else
        format.html { render action: "new" }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /journals/1
  # PUT /journals/1.json
  def update
    @journal = Journal.find(params[:id])

    respond_to do |format|
      if @journal.update_attributes(params[:journal])
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal = Journal.find(params[:id])
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to journals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Студент" %><br />
    <% # f.number_field :student_id  %>
    <%=  collection_select(:journal, :student_id, Student.all, :id, :name, {:prompt => true}) %>
  </div>
  <div class="field">
    <%= f.label "Предмет" %><br />
    <% # f.number_field :lesson_id %>
    <%=  collection_select(:journal, :lesson_id, Lesson.all, :id, :name, {:prompt => true}) %>
  </div>
  <div class="field">
    <%= f.label "Оценка" %><br />
    <%= f.text_field :mark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Редактирование отметки</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<h1>Оценки</h1>

<table>
  <tr>
    <th>Студент</th>
    <th>Предмет</th>
    <th>Оценка</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @journals.each do |journal| %>
  <tr>
    <td><%= Student.where(:id => journal.student_id).pluck(:name).first %>  </td>
    <td><%= Lesson.where(:id => journal.lesson_id).pluck(:name).first %></td>
    <td><%= journal.mark %></td>
    <td><%= link_to 'Показать', journal %></td>
    <td><%= link_to 'Редактировать', edit_journal_path(journal) %></td>
    <td><%= link_to 'Удалить', journal, method: :delete, data: { confirm: 'Точно?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новая отметка', new_journal_path %>

app/views/journals/new.html.erb
<h1>Новая отметка</h1>

<%= render 'form' %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <% # @journal.student_id %>
  <%= Student.where(:id => @journal.student_id).pluck(:name).first %>
</p>

<p>
  <b>Lesson:</b>
  <% #@journal.lesson_id %>
  <%= Lesson.where(:id => @journal.lesson_id).pluck(:name).first  %>
</p>

<p>
  <b>Mark:</b>
  <%= @journal.mark %>
</p>


<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <p>
      <b>Предметы и студенты с лучшей оценкой:</b>    <br>
        <% Lesson.all.each do |lesson| %>
          <tr>
            <% @students = Student.where(:id => Journal.order('mark desc').where(:lesson_id => lesson.id).pluck(:student_id).first).pluck(:name).first   %>

            <td>Студент с лучшей оценкой по <b><%= lesson.name  %></b>: <%= @students %> </td>
            <% # @journals = Journal.order('mark desc').where(:lesson_id => lesson.id).pluck(:student_id).first %>
            <% #@students = Student.where(:id => @journals).pluck(:name).first %>
             <% # @journals = Journal.where(:lesson_id => lesson.id).order('mark') %>
             <% #@journals = @journals.pluck(:student_id) %>
             <% #@students = Student.where(:id => @journals[1] ) %>
             <% #@students = @students.pluck(:name) %>
             <%  %>
            <br>
            <td><% %></td>
          </tr>
      <% end %>


  </nav>
</footer>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag :defaults  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Univer Application</title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets'  %>
  <%= javascript_include_tag "application" %>
</head>
<body>
<div class="container">
  <header>
      <nav class="round">
      <ul>
        <li><%= link_to "Студенты", 'students' %></li>
        <li><%= link_to "Предметы", 'lessons' %></li>
        <li><%= link_to "Оценки", 'journals' %></li>
      </ul>
    </nav>
  </header>
  <section class="round">
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<h1>Предметы:</h1>

<table>
  <tr>
    <th>Наименование</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lessons.each do |lesson| %>
  <tr>
    <td><%= lesson.name %></td>
    <td><%= link_to 'Показать', lesson %></td>
    <td><%= link_to 'Редактировать', edit_lesson_path(lesson) %></td>
    <td><%= link_to 'Удалить', lesson, method: :delete, data: { confirm: 'Точно?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новый предмет', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lesson.name %>
</p>


<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Редактирование информации</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Студенты:</h1>

<table>
  <tr>
    <th>Имя</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= link_to 'Показать', student %></td>
    <td><%= link_to 'Редактировать', edit_student_path(student) %></td>
    <td><%= link_to 'Удалить', student, method: :delete, data: { confirm: 'Точно?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новый студент', new_student_path %>

app/views/students/new.html.erb
<h1>Новый студент</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>